evaluation:
  base-url: http://4.224.186.213/evaluation-service
  depots-path: /depots
  auth-token: Bearer <paste-your-token-here>

server:
  port: 8080

logging:
  level:
    com.example.evaluation: DEBUG
